// Canonical list of all Indian states and union territories, shared by every
// form/select that asks the patient which state they're being treated in.
export const INDIAN_STATES_AND_UTS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export type IndianStateName = (typeof INDIAN_STATES_AND_UTS)[number];

// Display translations for every state/UT above, keyed by app language code.
// "Other" is kept as a fallback option for the rare edge case (e.g. NRI /
// unlisted address) even though the list above is otherwise exhaustive.
export const STATE_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "Andaman and Nicobar Islands": "Andaman and Nicobar Islands",
    "Andhra Pradesh": "Andhra Pradesh",
    "Arunachal Pradesh": "Arunachal Pradesh",
    Assam: "Assam",
    Bihar: "Bihar",
    Chandigarh: "Chandigarh",
    Chhattisgarh: "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu": "Dadra and Nagar Haveli and Daman and Diu",
    Delhi: "Delhi",
    Goa: "Goa",
    Gujarat: "Gujarat",
    Haryana: "Haryana",
    "Himachal Pradesh": "Himachal Pradesh",
    "Jammu & Kashmir": "Jammu & Kashmir",
    Jharkhand: "Jharkhand",
    Karnataka: "Karnataka",
    Kerala: "Kerala",
    Ladakh: "Ladakh",
    Lakshadweep: "Lakshadweep",
    "Madhya Pradesh": "Madhya Pradesh",
    Maharashtra: "Maharashtra",
    Manipur: "Manipur",
    Meghalaya: "Meghalaya",
    Mizoram: "Mizoram",
    Nagaland: "Nagaland",
    Odisha: "Odisha",
    Puducherry: "Puducherry",
    Punjab: "Punjab",
    Rajasthan: "Rajasthan",
    Sikkim: "Sikkim",
    "Tamil Nadu": "Tamil Nadu",
    Telangana: "Telangana",
    Tripura: "Tripura",
    "Uttar Pradesh": "Uttar Pradesh",
    Uttarakhand: "Uttarakhand",
    "West Bengal": "West Bengal",
    Other: "Other State",
  },
  hi: {
    "Andaman and Nicobar Islands": "अंडमान और निकोबार द्वीप समूह",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Arunachal Pradesh": "अरुणाचल प्रदेश",
    Assam: "असम",
    Bihar: "बिहार",
    Chandigarh: "चंडीगढ़",
    Chhattisgarh: "छत्तीसगढ़",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा और नगर हवेली और दमन और दीव",
    Delhi: "दिल्ली",
    Goa: "गोवा",
    Gujarat: "गुजरात",
    Haryana: "हरियाणा",
    "Himachal Pradesh": "हिमाचल प्रदेश",
    "Jammu & Kashmir": "जम्मू और कश्मीर",
    Jharkhand: "झारखंड",
    Karnataka: "कर्नाटक",
    Kerala: "केरल",
    Ladakh: "लद्दाख",
    Lakshadweep: "लक्षद्वीप",
    "Madhya Pradesh": "मध्य प्रदेश",
    Maharashtra: "महाराष्ट्र",
    Manipur: "मणिपुर",
    Meghalaya: "मेघालय",
    Mizoram: "मिज़ोरम",
    Nagaland: "नागालैंड",
    Odisha: "ओडिशा",
    Puducherry: "पुडुचेरी",
    Punjab: "पंजाब",
    Rajasthan: "राजस्थान",
    Sikkim: "सिक्किम",
    "Tamil Nadu": "तमिलनाडु",
    Telangana: "तेलंगाना",
    Tripura: "त्रिपुरा",
    "Uttar Pradesh": "उत्तर प्रदेश",
    Uttarakhand: "उत्तराखंड",
    "West Bengal": "पश्चिम बंगाल",
    Other: "अन्य राज्य",
  },
  mr: {
    "Andaman and Nicobar Islands": "अंदमान आणि निकोबार बेटे",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Arunachal Pradesh": "अरुणाचल प्रदेश",
    Assam: "आसाम",
    Bihar: "बिहार",
    Chandigarh: "चंदीगड",
    Chhattisgarh: "छत्तीसगड",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा आणि नगर हवेली आणि दमण आणि दीव",
    Delhi: "दिल्ली",
    Goa: "गोवा",
    Gujarat: "गुजरात",
    Haryana: "हरियाणा",
    "Himachal Pradesh": "हिमाचल प्रदेश",
    "Jammu & Kashmir": "जम्मू आणि काश्मीर",
    Jharkhand: "झारखंड",
    Karnataka: "कर्नाटक",
    Kerala: "केरल",
    Ladakh: "लडाख",
    Lakshadweep: "लक्षद्वीप",
    "Madhya Pradesh": "मध्य प्रदेश",
    Maharashtra: "महाराष्ट्र",
    Manipur: "मणिपूर",
    Meghalaya: "मेघालय",
    Mizoram: "मिझोराम",
    Nagaland: "नागालँड",
    Odisha: "ओडिशा",
    Puducherry: "पुडुचेरी",
    Punjab: "पंजाब",
    Rajasthan: "राजस्थान",
    Sikkim: "सिक्कीम",
    "Tamil Nadu": "तमिळनाडू",
    Telangana: "तेलंगणा",
    Tripura: "त्रिपुरा",
    "Uttar Pradesh": "उत्तर प्रदेश",
    Uttarakhand: "उत्तराखंड",
    "West Bengal": "पश्चिम बंगाल",
    Other: "इतर राज्य",
  },
  kn: {
    "Andaman and Nicobar Islands": "ಅಂಡಮಾನ್ ಮತ್ತು ನಿಕೋಬಾರ್ ದ್ವೀಪಗಳು",
    "Andhra Pradesh": "ಆಂಧ್ರ ಪ್ರದೇಶ",
    "Arunachal Pradesh": "ಅರುಣಾಚಲ ಪ್ರದೇಶ",
    Assam: "ಅಸ್ಸಾಂ",
    Bihar: "ಬಿಹಾರ",
    Chandigarh: "ಚಂಡೀಗಢ",
    Chhattisgarh: "ಛತ್ತೀಸ್‌ಗಢ",
    "Dadra and Nagar Haveli and Daman and Diu": "ದಾದ್ರಾ ಮತ್ತು ನಗರ ಹವೇಲಿ ಮತ್ತು ದಮನ್ ಮತ್ತು ದಿಯು",
    Delhi: "ದೆಹಲಿ",
    Goa: "ಗೋವಾ",
    Gujarat: "ಗುಜರಾತ್",
    Haryana: "ಹರಿಯಾಣ",
    "Himachal Pradesh": "ಹಿಮಾಚಲ ಪ್ರದೇಶ",
    "Jammu & Kashmir": "ಜಮ್ಮು ಮತ್ತು ಕಾಶ್ಮೀರ",
    Jharkhand: "ಜಾರ್ಖಂಡ್",
    Karnataka: "ಕರ್ನಾಟಕ",
    Kerala: "ಕೇರಳ",
    Ladakh: "ಲಡಾಖ್",
    Lakshadweep: "ಲಕ್ಷದ್ವೀಪ",
    "Madhya Pradesh": "ಮಧ್ಯಪ್ರದೇಶ",
    Maharashtra: "ಮಹಾರಾಷ್ಟ್ರ",
    Manipur: "ಮಣಿಪುರ",
    Meghalaya: "ಮೇಘಾಲಯ",
    Mizoram: "ಮಿಜೋರಾಂ",
    Nagaland: "ನಾಗಾಲ್ಯಾಂಡ್",
    Odisha: "ಒಡಿಸ್ಸಾ",
    Puducherry: "ಪುದುಚೇರಿ",
    Punjab: "ಪಂಜಾಬ್",
    Rajasthan: "ರಾಜಸ್ಥಾನ",
    Sikkim: "ಸಿಕ್ಕಿಂ",
    "Tamil Nadu": "ತಮಿಳುನಾಡು",
    Telangana: "ತೆಲಂಗಾಣ",
    Tripura: "ತ್ರಿಪುರ",
    "Uttar Pradesh": "ಉತ್ತರ ಪ್ರದೇಶ",
    Uttarakhand: "ಉತ್ತರಾಖಂಡ",
    "West Bengal": "ಪಶ್ಚಿಮ ಬಂಗಾಳ",
    Other: "ಇತರ ರಾಜ್ಯ",
  },
  bn: {
    "Andaman and Nicobar Islands": "আন্দামান ও নিকোবর দ্বীপপুঞ্জ",
    "Andhra Pradesh": "অন্ধ্রপ্রদেশ",
    "Arunachal Pradesh": "অরুণাচল প্রদেশ",
    Assam: "আসাম",
    Bihar: "বিহার",
    Chandigarh: "চণ্ডীগড়",
    Chhattisgarh: "ছত্তীসগঢ়",
    "Dadra and Nagar Haveli and Daman and Diu": "দাদরা ও নগর হাভেলি এবং দমন ও দিউ",
    Delhi: "দিল্লি",
    Goa: "গোয়া",
    Gujarat: "গুজরাট",
    Haryana: "হরিয়ানা",
    "Himachal Pradesh": "হিমাচল প্রদেশ",
    "Jammu & Kashmir": "জম্মু ও কাশ্মীর",
    Jharkhand: "ঝাড়খণ্ড",
    Karnataka: "কর্ণাটক",
    Kerala: "কেরালা",
    Ladakh: "লাদাখ",
    Lakshadweep: "লক্ষদ্বীপ",
    "Madhya Pradesh": "মধ্যপ্রদেশ",
    Maharashtra: "মহারাষ্ট্র",
    Manipur: "মণিপুর",
    Meghalaya: "মেঘালয়",
    Mizoram: "মিজোরাম",
    Nagaland: "নাগাল্যান্ড",
    Odisha: "ওড়িশা",
    Puducherry: "পুদুচেরি",
    Punjab: "পাঞ্জাব",
    Rajasthan: "রাজস্থান",
    Sikkim: "সিকিম",
    "Tamil Nadu": "তামিলনাড়ু",
    Telangana: "তেলেঙ্গানা",
    Tripura: "ত্রিপুরা",
    "Uttar Pradesh": "উত্তরপ্রদেশ",
    Uttarakhand: "উত্তরাখণ্ড",
    "West Bengal": "পশ্চিমবঙ্গ",
    Other: "অন্যান্য রাজ্য",
  },
};

export function getStateLabel(state: string, language: string): string {
  const dict = STATE_TRANSLATIONS[language] || STATE_TRANSLATIONS.en;
  return dict[state] || state;
}
